#!/bin/sh

version='0.1.4'
beta=''

make clean
rm -f config.cache
rm -f Makefile
rm -f config.h
rm -f config.log
rm -f config.status
rm -f stamp*
rm -f po/*.gmo
rm -rf src/.deps
cd ..
tar -hzcvf gadmin-squid-$version$beta.tar.gz gadmin-squid-$version
